name: ialarm-mqtt issues
description: Report issues related to ialarm-mqtt
title: "[bug]: "
labels: ["bug"]
assignees:
  - maxill1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.10.1 (Default)
        - 0.11.1 (Edge/Development)
    validations:
      required: true        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true  
  - type: dropdown
    id: environment
    attributes:
      label: Where are you running ialarm-mqtt?
      multiple: true
      options:
        - Hass.io addon
        - docker
        - node/npx
    validations:
      required: true   
  - type: input
    id: alarm
    attributes:
      label: Alarm panel model
      description: Brand and version of your alarm panel (antifurto365, casasicura, meian, focus, and)
      placeholder: ex. Focus FC-7688Plus
    validations:
      required: true    
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
